### ISSUE TITLE
wrong fr translation for multiple entries

### ISSUE THREAD

**Issue by Flyingmana** [mageplaza/magento-2-french-language-pack#15]
Multiple translations are wrongfully translated with 

> Votre commande est en cours de traitement et vous recevrez bientôt un mail avec les détails de la commande. Quand la commande sera expédiée, vous recevrez un autre mail avec un lien pour suivre l'avancement de la livraison

**Comment by MyoDaisy** [comment]
If you find that there are many incorrect translations, you can contribute to us by following the instructions in this link: [https://github.com/mageplaza/magento-2-french-language-pack/blob/master/HOW-TO-CONTRIBUTE.md](https://github.com/mageplaza/magento-2-french-language-pack/blob/master/HOW-TO-CONTRIBUTE.md).
Thank you so much!
