### ISSUE TITLE
Empty fr_FR.csv file

### ISSUE THREAD

**Issue by delyriand** [mageplaza/magento-2-french-language-pack#18]
The CSV `fr_FR.csv` file has been emptied and completeness increased to 0%.

Please, revert your last commit or regenerate this file :)

**Comment by delyriand** [comment]
Why 2 CSV files ? `fr_FR.csv` and `github_contributions.csv` ?

It looks like magento loads the 2 files. And the github in second so he overwrites the translations of the first file.

Example: 
* fr_FR.csv: `"Product that you are trying to add is not available.","Le produit que vous essayez d'ajouter n'est pas disponible.",module,Magento_Quote`
* github_contribution.csv: `"Product that you are trying to add is not available.","Product that you are trying to add is not available."`

Finally, my string is not translated

**Comment by MyoDaisy** [comment]
Thanks for your report and sorry for any inconvenience.
We have fixed empty file issue. Please update the latest version or rollback to previous.

You right, Magento loads the 2 **csv** files. And the **github_contribution** overwrites the translations of **fr_FR.csv**. So you can edit the wrong phrase in **github_contribution.csv**
