### ISSUE TITLE
Add Semantic Versioning

### ISSUE THREAD

**Issue by larsroettig** [mageplaza/magento-2-french-language-pack#19]
As a developer is better to use a tag with  Semantic Versioning for Composer Versioning.

**Comment by ihor-sviziev** [comment]
@imsamthomas could you add tag to this repo?

**Comment by MyoDaisy** [comment]
Thank you for your response. I added tags to this repo.

**Comment by ihor-sviziev** [comment]
Hi @MyoDaisy,
Could you do the same for https://github.com/mageplaza/magento-2-german-language-pack/issues/10?
Than you!
