### ISSUE TITLE
Override translation in another module

### ISSUE THREAD

**Issue by Seb33300** [mageplaza/magento-2-french-language-pack#24]
Hello,

In my custom module, I am trying to override a translation that has already be set by the `magento-2-french-language-pack` but it looks like `magento-2-french-language-pack` always takes the priority.

I am not able to override the translations.
The translation provided by `magento-2-french-language-pack` is always displayed.

Is there a solution?

**Comment by younes0** [comment]
@Seb33300 did you get the solution ?

**Comment by Seb33300** [comment]
Languages packs have a higher priority on modules.

So you have to create a custom language pack in order to override translations from this repository.
