### ISSUE TITLE
Wrong translation for "Yes" to French

### ISSUE THREAD

**Issue by lbajsarowicz** [mageplaza/magento-2-french-language-pack#9]
### Expected behaviour

`Yes` should be translated to `Oui` in the application.

### Current behaviour

`Yes` displays as `Oui (Make sure you keep it in a safe place.)` for all the places

### Reason

`Yes` is being translated to `Oui"(Make sure you keep it in a safe place.)` in translation CSV file.

### Attachments

<img width="847" alt="zrzut ekranu 2018-03-06 o 14 02 02" src="https://user-images.githubusercontent.com/1639941/37033660-00dd97c4-2147-11e8-840c-5a52797bd71e.png">
<img width="659" alt="zrzut ekranu 2018-03-06 o 14 01 39" src="https://user-images.githubusercontent.com/1639941/37033661-011baadc-2147-11e8-9330-258dfc70e218.png">
<img width="653" alt="zrzut ekranu 2018-03-06 o 14 01 15" src="https://user-images.githubusercontent.com/1639941/37033662-013cb6d2-2147-11e8-985a-bfc4dc964ca6.png">

**Comment by nimitaemipro** [comment]
there are many strings which are concatenate English  string like:
Vat number
Website
Sort Order
Start Time
Separate by ",".
Weekly
 and many more strings have same issues. please update csv.

**Comment by zebeel** [comment]
Hi there,
We have provided github_contributions.csv
You guys can contribute the translation in this file, we will merge the new translation to fr_FR.csv
